[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "segmensation-rtd"
authors = [{name = "Eckert", email = "manuel.eckert@stud.htwk-leipzig.de"}]
dynamic = ["version", "description"]
